package com.spring.erdem.model;

public enum Fach {
	DEUTSCH, MATHEMATIK,ENGLISCH, BIOLOGIE, CHEMIE, PHYSIK, INFORMATIK, ERDKUNDE,
	GESCHICHTE, GEOGRAFIE, ETHIK, LATEIN, FRANZOESISCH, SPANISCH, KUNST, MUSIK;
}
